const LS_LINKS="ql_links_v1",LS_CATS="ql_categories_v1";
let links=load(LS_LINKS,[])||[],categories=load(LS_CATS,[])||[];
let ui={layout:document.documentElement.dataset.layout||"grid",linkStyle:document.documentElement.dataset.linkStyle||"classic",favicons:document.documentElement.dataset.showFavicons==="true",theme:document.documentElement.dataset.theme||"light",reorder:document.documentElement.dataset.reorder||"drag",tldList:[],tldActive:new Set([".com"]),font:{source:"default",builtIn:null,local:null,urlCss:null,urlFamily:null}};
const $=q=>document.querySelector(q),$$=q=>Array.from(document.querySelectorAll(q));
const yearEl=$("#year"),linksContainer=$("#linksContainer"),linkCount=$("#linkCount"),categoriesEl=$("#categories");
const btnAddLink=$("#btnAddLink"),btnAddCategory=$("#btnAddCategory"),fileImport=$("#fileImport"),btnImport=$("#btnImport"),btnExport=$("#btnExport");
const settingsOverlay=$("#settingsOverlay"),btnOpenSettings=$("#btnOpenSettings"),btnCloseSettings=$("#btnCloseSettings"),toggleFavicons=$("#toggleFavicons");
const linkOverlay=$("#linkOverlay"),btnCloseLink=$("#btnCloseLink"),linkModalTitle=$("#linkModalTitle"),fldTitle=$("#fldTitle"),fldURL=$("#fldURL"),fldCategory=$("#fldCategory"),fldNewCategory=$("#fldNewCategory"),fldNewTab=$("#fldNewTab"),fldColorPicker=$("#fldColorPicker"),fldR=$("#fldR"),fldG=$("#fldG"),fldB=$("#fldB"),rgbPreview=$("#rgbPreview"),btnSaveLink=$("#btnSaveLink"),btnDeleteLink=$("#btnDeleteLink"),palette=$("#palette");
const tldListEl=$("#tldList"),tldSearch=$("#tldSearch"),btnActivateCom=$("#btnActivateCom");
const fontBuiltInRow=$("#fontBuiltInRow"),fontLocalRow=$("#fontLocalRow"),fontUrlRow=$("#fontUrlRow"),fontBuiltIn=$("#fontBuiltIn"),fontLocal=$("#fontLocal"),fontUrl=$("#fontUrl"),fontFamilyUrl=$("#fontFamilyUrl"),btnApplyUrlFont=$("#btnApplyUrlFont");
let editingId=null,activeCatId=null,drag={type:null,id:null,ghost:null,offsetX:0,offsetY:0,placeholder:null};

function load(k,f){try{const v=JSON.parse(localStorage.getItem(k));return v??f}catch{return f}}
function save(k,v){localStorage.setItem(k,JSON.stringify(v))}
function uid(){return Math.random().toString(36).slice(2,10)}
function hexToRGB(hex){const h=hex.replace("#","");if(h.length===3)return{r:parseInt(h[0]+h[0],16),g:parseInt(h[1]+h[1],16),b:parseInt(h[2]+h[2],16)};return{r:parseInt(h.slice(0,2),16),g:parseInt(h.slice(2,4),16),b:parseInt(h.slice(4,6),16)}}
function RGBToHex(r,g,b){const to=v=>Math.max(0,Math.min(255,Number(v)|0)).toString(16).padStart(2,"0");return"#"+to(r)+to(g)+to(b)}
function setLayout(v){ui.layout=v;document.documentElement.setAttribute("data-layout",v);linksContainer.className=v==="grid"?"links-grid":"links-list"}
function setLinkStyle(v){ui.linkStyle=v;document.documentElement.setAttribute("data-link-style",v)}
function setFavicons(on){ui.favicons=!!on;document.documentElement.setAttribute("data-show-favicons",on?"true":"false")}
function setTheme(v){ui.theme=v;const m=matchMedia("(prefers-color-scheme: dark)").matches;const mode=v==="auto"?(m?"dark-elegant":"light"):v;document.documentElement.setAttribute("data-theme",mode)}
function setReorder(v){ui.reorder=v;document.documentElement.setAttribute("data-reorder",v);renderLinks()}
function ensureDefaults(){if(categories.length===0){categories=[{id:uid(),name:"Uncategorized"},{id:uid(),name:"Work"},{id:uid(),name:"Personal"}];save(LS_CATS,categories)}if(links.length===0){const c=categories[0].id;links=[{id:uid(),title:"Google",url:"https://www.google.com",catId:c,color:"#2563eb",target:"_blank"},{id:uid(),title:"YouTube",url:"https://www.youtube.com",catId:c,color:"#ef4444",target:"_blank"},{id:uid(),title:"GitHub",url:"https://github.com",catId:c,color:"#111827",target:"_blank"},{id:uid(),title:"Wikipedia",url:"https://www.wikipedia.org",catId:c,color:"#10b981",target:"_blank"}];save(LS_LINKS,links)}}
function renderCategories(){categoriesEl.innerHTML="";categories.forEach(cat=>{const b=document.createElement("button");b.className="category-pill";b.textContent=cat.name;b.dataset.id=cat.id;b.draggable=false;b.onclick=()=>toggleCategory(cat.id);enableCatDrag(b);categoriesEl.appendChild(b)})}
function toggleCategory(id){activeCatId=activeCatId===id?null:id;$$(".category-pill").forEach(p=>p.classList.toggle("active",p.dataset.id===activeCatId));renderLinks()}
function faviconURL(u){try{return new URL(u).origin+"/favicon.ico"}catch{return""}}
function linkItem(l){const item=document.createElement("div");item.className="link-item";item.dataset.id=l.id;item.style.borderColor=l.color;const fav=document.createElement("img");fav.className="favicon";fav.src=faviconURL(l.url);const block=document.createElement("div");block.style.flex="1 1 auto";block.style.minWidth="0";const t=document.createElement("div");t.className="link-title";t.textContent=l.title;const u=document.createElement("div");u.className="link-url";u.textContent=l.url;block.append(t,u);const col=document.createElement("div");col.className="link-col";const dot=document.createElement("span");dot.className="color-dot";dot.style.background=l.color;const open=document.createElement("button");open.className="small-btn";open.textContent="Open";open.onclick=()=>window.open(l.url,l.target||"_blank","noopener");const edit=document.createElement("button");edit.className="small-btn";edit.textContent="Edit";edit.onclick=()=>openLinkEditor(l.id);const del=document.createElement("button");del.className="small-btn";del.textContent="Remove";del.onclick=()=>{links=links.filter(x=>x.id!==l.id);save(LS_LINKS,links);renderLinks()};col.append(dot,open,edit,del);item.append(fav,block,col);if(ui.reorder==="drag")enableLinkDrag(item);else enableLinkButtons(item);return item}
function enableLinkButtons(item){const up=document.createElement("button"),down=document.createElement("button");up.className="small-btn";down.className="small-btn";up.textContent="↑";down.textContent="↓";const col=item.querySelector(".link-col");col.append(up,down);up.onclick=()=>moveItem(item.dataset.id,-1);down.onclick=()=>moveItem(item.dataset.id,1)}
function moveItem(id,delta){const i=links.findIndex(x=>x.id===id);if(i<0)return;const j=Math.max(0,Math.min(links.length-1,i+delta));if(i===j)return;const [m]=links.splice(i,1);links.splice(j,0,m);save(LS_LINKS,links);renderLinks()}
function renderLinks(){linksContainer.innerHTML="";let list=links.slice();if(activeCatId)list=list.filter(l=>l.catId===activeCatId);linkCount.textContent=`${list.length} ${list.length===1?"link":"links"}`;list.forEach(l=>linksContainer.appendChild(linkItem(l)))}
function enableLinkDrag(el){el.style.touchAction="none";el.addEventListener("pointerdown",e=>startDrag(e,el,"link"))}
function enableCatDrag(el){el.style.touchAction="none";el.addEventListener("pointerdown",e=>startDrag(e,el,"category"))}
function startDrag(e,el,type){drag.type=type;drag.id=el.dataset.id;const r=el.getBoundingClientRect();drag.offsetX=e.clientX-r.left;drag.offsetY=e.clientY-r.top;drag.ghost=el.cloneNode(true);drag.ghost.classList.add("dragging");drag.ghost.style.position="fixed";drag.ghost.style.left=r.left+"px";drag.ghost.style.top=r.top+"px";drag.ghost.style.width=r.width+"px";drag.ghost.style.pointerEvents="none";document.body.appendChild(drag.ghost);drag.placeholder=document.createElement("div");drag.placeholder.className="placeholder";drag.placeholder.style.width=r.width+"px";drag.placeholder.style.height=r.height+"px";el.parentElement.insertBefore(drag.placeholder,el);el.style.display="none";document.addEventListener("pointermove",onDragMove);document.addEventListener("pointerup",onDragEnd,{once:true})}
function onDragMove(e){if(!drag.ghost)return;drag.ghost.style.left=(e.clientX-drag.offsetX)+"px";drag.ghost.style.top=(e.clientY-drag.offsetY)+"px";if(drag.type==="link"){const c=linksContainer;if(!c)return;const siblings=[...c.children].filter(n=>n!==drag.placeholder);let ins=false;for(const s of siblings){const r=s.getBoundingClientRect();const before=e.clientY<r.top+r.height/2;if(before){c.insertBefore(drag.placeholder,s);ins=true;break}}if(!ins)c.appendChild(drag.placeholder)}else{const pills=[...document.querySelectorAll(".category-pill")].filter(p=>p!==drag.placeholder);let ins=false;for(const p of pills){const r=p.getBoundingClientRect();const before=e.clientX<r.left+r.width/2;if(before){p.parentElement.insertBefore(drag.placeholder,p);ins=true;break}}if(!ins)categoriesEl.appendChild(drag.placeholder)}}
function onDragEnd(){if(!drag.ghost)return;drag.ghost.remove();drag.ghost=null;if(drag.type==="link"){const ordered=[...linksContainer.children].filter(n=>n.classList.contains("link-item")||n===drag.placeholder).map(n=>n===drag.placeholder?drag.id:n.dataset.id);const map=new Map(links.map(l=>[l.id,l]));links=ordered.map(id=>map.get(id)).concat(links.filter(l=>!ordered.includes(l.id)));save(LS_LINKS,links);renderLinks()}else{const ids=[...categoriesEl.children].filter(n=>n.classList&&n.classList.contains("category-pill")).map(n=>n.dataset.id);const map=new Map(categories.map(c=>[c.id,c]));categories=ids.map(id=>map.get(id));save(LS_CATS,categories);renderCategories()}cleanupDrag()}
function cleanupDrag(){const ph=drag.placeholder;if(ph&&ph.parentElement)ph.parentElement.removeChild(ph);drag={type:null,id:null,ghost:null,offsetX:0,offsetY:0,placeholder:null}}
function openLinkEditor(id){editingId=id;populateCategoriesSelect();if(id){const l=links.find(x=>x.id===id);linkModalTitle.textContent="Edit Link";fldTitle.value=l.title;fldURL.value=l.url;fldNewTab.checked=(l.target!=="_self");fldCategory.value=l.catId;fldNewCategory.value="";setColor(l.color);btnDeleteLink.classList.remove("hidden")}else{linkModalTitle.textContent="Add Link";fldTitle.value="";fldURL.value="";fldNewTab.checked=true;fldCategory.value=categories[0]?.id||"";fldNewCategory.value="";setColor("#2563eb");btnDeleteLink.classList.add("hidden")}linkOverlay.classList.add("open");linkOverlay.setAttribute("aria-hidden","false")}
function populateCategoriesSelect(){fldCategory.innerHTML="";categories.forEach(c=>{const o=document.createElement("option");o.value=c.id;o.textContent=c.name;fldCategory.appendChild(o)})}
function setColor(hex){const {r,g,b}=hexToRGB(hex);fldColorPicker.value=hex;fldR.value=r;fldG.value=g;fldB.value=b;rgbPreview.textContent=hex.toLowerCase();$$(".swatch").forEach(s=>s.setAttribute("aria-selected","false"));const m=[...palette.children].find(s=>s.dataset.color?.toLowerCase()===hex.toLowerCase());if(m)m.setAttribute("aria-selected","true")}
function saveLink(){const title=fldTitle.value.trim(),url=fldURL.value.trim();if(!title||!url)return;let catId=fldCategory.value;const newCat=fldNewCategory.value.trim();if(newCat){const c={id:uid(),name:newCat};categories.push(c);save(LS_CATS,categories);catId=c.id}const color=fldColorPicker.value;const target=fldNewTab.checked?"_blank":"_self";if(editingId){const i=links.findIndex(x=>x.id===editingId);if(i>-1)links[i]={...links[i],title,url,catId,color,target}}else{links.push({id:uid(),title,url,catId,color,target})}save(LS_LINKS,links);closeLinkModal();renderCategories();renderLinks()}
function deleteLink(){if(!editingId)return;links=links.filter(x=>x.id!==editingId);save(LS_LINKS,links);closeLinkModal();renderLinks()}
function closeLinkModal(){linkOverlay.classList.remove("open");linkOverlay.setAttribute("aria-hidden","true")}
function buildPalette(){const colors=["#2563eb","#10b981","#ef4444","#f59e0b","#6b7280","#111827","#22c55e","#8b5cf6","#06b6d4","#eab308"];palette.innerHTML="";colors.forEach(c=>{const b=document.createElement("button");b.className="swatch";b.style.background=c;b.dataset.color=c;b.onclick=()=>setColor(c);palette.appendChild(b)});setColor(colors[0])}
function syncRGB(){const fromRGB=()=>{const hex=RGBToHex(fldR.value,fldG.value,fldB.value);fldColorPicker.value=hex;rgbPreview.textContent=hex};const fromPicker=()=>{const {r,g,b}=hexToRGB(fldColorPicker.value);fldR.value=r;fldG.value=g;fldB.value=b;rgbPreview.textContent=fldColorPicker.value.toLowerCase()};[fldR,fldG,fldB].forEach(i=>i.addEventListener("input",fromRGB));fldColorPicker.addEventListener("input",fromPicker)}
function importJSON(){fileImport.value="";fileImport.click()}
function onImportFile(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const data=JSON.parse(r.result);if(Array.isArray(data.links))links=data.links;if(Array.isArray(data.categories))categories=data.categories;save(LS_LINKS,links);save(LS_CATS,categories);renderCategories();renderLinks()}catch{}};r.readAsText(f)}
function exportJSON(){const data={links,categories};const blob=new Blob([JSON.stringify(data)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="quick-links.json";document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(url);a.remove()},0)}
function openSettings(){settingsOverlay.classList.add("open");settingsOverlay.setAttribute("aria-hidden","false")}
function closeSettings(){settingsOverlay.classList.remove("open");settingsOverlay.setAttribute("aria-hidden","true")}
async function loadTLDs(){try{const r=await fetch("https://data.iana.org/TLD/tlds-alpha-by-domain.txt",{cache:"no-store"});if(!r.ok)throw 0;const t=await r.text();const lines=t.split(/\r?\n/).filter(x=>x&&!x.startsWith("#")).map(x=>"."+x.toLowerCase());const set=new Set([".com",...lines]);ui.tldList=Array.from(set)}catch{ui.tldList=[".com",".it",".ru",".org",".net",".co",".uk",".de",".fr",".es",".io",".ai",".app",".dev",".jp",".kr",".cn",".br",".au",".ca",".mx",".ar",".ch",".se",".no",".nl",".be",".pt",".pl",".cz",".sk",".ro",".hu",".gr",".tr",".ua",".online",".site",".blog",".shop",".gov",".edu",".mil",".info",".biz",".tv",".fm",".museum",".aero",".cat",".asia",".tel",".name",".pro",".gg",".su",".xn--p1ai",".xn--fiqs8s",".xn--mk1bu44c"]}renderTLDs()}
function renderTLDs(){const q=tldSearch.value.trim().toLowerCase();tldListEl.innerHTML="";ui.tldList.filter(t=>!q||t.includes(q)).forEach(t=>{const row=document.createElement("div");row.className="form-row";const cb=document.createElement("input");cb.type="checkbox";cb.checked=ui.tldActive.has(t);cb.onchange=()=>{if(cb.checked)ui.tldActive.add(t);else ui.tldActive.delete(t)};const lab=document.createElement("label");lab.append(cb,document.createTextNode(" Activate "+t));row.append(lab);tldListEl.appendChild(row)})}
function setLayoutButtons(){$$('.layout-switch .small-btn').forEach(b=>b.addEventListener("click",()=>setLayout(b.dataset.layout)))}
function setSettingsBindings(){toggleFavicons.checked=ui.favicons;toggleFavicons.onchange=()=>setFavicons(toggleFavicons.checked);$$('input[name="theme"]').forEach(r=>r.onchange=()=>setTheme(r.value));$$('input[name="linkStyle"]').forEach(r=>r.onchange=()=>setLinkStyle(r.value));$$('input[name="layout"]').forEach(r=>r.onchange=()=>setLayout(r.value));$$('input[name="reorder"]').forEach(r=>r.onchange=()=>setReorder(r.value));$$('input[name="fontSource"]').forEach(r=>r.onchange=onFontSourceChange);btnApplyUrlFont.onclick=applyUrlFont;btnActivateCom.onclick=()=>{ui.tldActive=new Set([".com"]);renderTLDs()};tldSearch.oninput=renderTLDs()}
function onFontSourceChange(e){const v=e.target.value;ui.font.source=v;fontBuiltInRow.style.display=v==="builtin"?"":"none";fontLocalRow.style.display=v==="local"?"":"none";fontUrlRow.style.display=v==="url"?"":"none";if(v==="default")applyFontStack(defaultFontStack());if(v==="system")applyFontStack(systemFontStack());if(v==="builtin")applyBuiltInSelected();if(v==="local")detectLocalFonts();if(v==="url"){}}
function applyBuiltInSelected(){const fam=fontBuiltIn.value;applyBuiltInFont(fam)}
function applyUrlFont(){const css=fontUrl.value.trim(),fam=fontFamilyUrl.value.trim();if(!css||!fam)return;applyExternalCssFont(css,fam)}
function defaultFontStack(){return '"Plus Jakarta Sans", "Inter", ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif'}
function systemFontStack(){return 'ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif'}
function applyFontStack(stack){document.body.style.fontFamily=stack}
function injectStyle(css,id){let el=document.getElementById(id);if(!el){el=document.createElement("style");el.id=id;document.head.appendChild(el)}el.textContent=css}
function applyExternalCssFont(cssUrl,family){const id="ext_font_css";let link=document.getElementById(id);if(!link){link=document.createElement("link");link.id=id;link.rel="stylesheet";document.head.appendChild(link)}link.href=cssUrl;document.body.style.fontFamily=`"${family}", `+systemFontStack()}
const BUILTIN_FONTS=[
  {family:"Inter",files:{400:"fonts/inter-regular.woff2",600:"fonts/inter-semibold.woff2",700:"fonts/inter-bold.woff2"}},
  {family:"Poppins",files:{400:"fonts/poppins-regular.woff2",600:"fonts/poppins-semibold.woff2",700:"fonts/poppins-bold.woff2"}},
  {family:"Montserrat",files:{400:"fonts/montserrat-regular.woff2",600:"fonts/montserrat-semibold.woff2",700:"fonts/montserrat-bold.woff2"}},
  {family:"Nunito",files:{400:"fonts/nunito-regular.woff2",600:"fonts/nunito-semibold.woff2",700:"fonts/nunito-bold.woff2"}},
  {family:"Lato",files:{400:"fonts/lato-regular.woff2",700:"fonts/lato-bold.woff2",600:"fonts/lato-bold.woff2"}},
  {family:"Work Sans",files:{400:"fonts/worksans-regular.woff2",600:"fonts/worksans-semibold.woff2",700:"fonts/worksans-bold.woff2"}},
  {family:"Plus Jakarta Sans",files:{400:"fonts/plusjakarta-regular.woff2",600:"fonts/plusjakarta-semibold.woff2",700:"fonts/plusjakarta-bold.woff2"}},
  {family:"Manrope",files:{400:"fonts/manrope-regular.woff2",600:"fonts/manrope-semibold.woff2",700:"fonts/manrope-bold.woff2"}},
  {family:"DM Sans",files:{400:"fonts/dmsans-regular.woff2",600:"fonts/dmsans-semibold.woff2",700:"fonts/dmsans-bold.woff2"}},
  {family:"Space Grotesk",files:{400:"fonts/spacegrotesk-regular.woff2",600:"fonts/spacegrotesk-semibold.woff2",700:"fonts/spacegrotesk-bold.woff2"}},
  {family:"IBM Plex Sans",files:{400:"fonts/ibmplexsans-regular.woff2",600:"fonts/ibmplexsans-semibold.woff2",700:"fonts/ibmplexsans-bold.woff2"}},
  {family:"Exo 2",files:{400:"fonts/exo2-regular.woff2",600:"fonts/exo2-semibold.woff2",700:"fonts/exo2-bold.woff2"}},
  {family:"Oxygen",files:{400:"fonts/oxygen-regular.woff2",700:"fonts/oxygen-bold.woff2",600:"fonts/oxygen-bold.woff2"}},
  {family:"Bebas Neue",files:{400:"fonts/bebasneue-regular.woff2",600:"fonts/bebasneue-regular.woff2",700:"fonts/bebasneue-regular.woff2"}},
  {family:"Rubik",files:{400:"fonts/rubik-regular.woff2",600:"fonts/rubik-semibold.woff2",700:"fonts/rubik-bold.woff2"}},
  {family:"Titillium Web",files:{400:"fonts/titillium-regular.woff2",600:"fonts/titillium-semibold.woff2",700:"fonts/titillium-bold.woff2"}},
  {family:"Cairo",files:{400:"fonts/cairo-regular.woff2",600:"fonts/cairo-semibold.woff2",700:"fonts/cairo-bold.woff2"}},
  {family:"PT Sans",files:{400:"fonts/ptsans-regular.woff2",700:"fonts/ptsans-bold.woff2",600:"fonts/ptsans-bold.woff2"}},
  {family:"Open Sans",files:{400:"fonts/opensans-regular.woff2",600:"fonts/opensans-semibold.woff2",700:"fonts/opensans-bold.woff2"}},
  {family:"Raleway",files:{400:"fonts/raleway-regular.woff2",600:"fonts/raleway-semibold.woff2",700:"fonts/raleway-bold.woff2"}}
];
function populateBuiltInFonts(){fontBuiltIn.innerHTML="";BUILTIN_FONTS.forEach(f=>{const o=document.createElement("option");o.value=f.family;o.textContent=f.family;fontBuiltIn.appendChild(o)});fontBuiltIn.onchange=applyBuiltInSelected}
function applyBuiltInFont(family){const def=BUILTIN_FONTS.find(x=>x.family===family)||BUILTIN_FONTS[0];const css=`@font-face{font-family:"${def.family}";src:url("${def.files[400]}") format("woff2");font-weight:400;font-style:normal;font-display:swap}
@font-face{font-family:"${def.family}";src:url("${def.files[600]}") format("woff2");font-weight:600;font-style:normal;font-display:swap}
@font-face{font-family:"${def.family}";src:url("${def.files[700]}") format("woff2");font-weight:700;font-style:normal;font-display:swap}`;injectStyle(css,"builtin_fonts_css");applyFontStack(`"${def.family}", `+systemFontStack())}
function detectLocalFonts(){fontLocal.innerHTML="";const candidates=["Segoe UI","SF Pro Text","San Francisco","Roboto","Arial","Helvetica","Inter","Poppins","Montserrat","Open Sans","Lato","Nunito","Manrope"];const test=document.createElement("span");test.style.position="absolute";test.style.left="-9999px";test.style.fontSize="72px";test.textContent="mmmmmmmmmmlllliiiiWWWW";document.body.appendChild(test);const defW=measureFont(test,"monospace");candidates.forEach(f=>{const w=measureFont(test,`${f}, monospace`);if(w!==defW){const o=document.createElement("option");o.value=f;o.textContent=f;fontLocal.appendChild(o)}});document.body.removeChild(test);fontLocal.onchange=()=>applyFontStack(`"${fontLocal.value}", `+systemFontStack());if(fontLocal.options.length>0)applyFontStack(`"${fontLocal.options[0].value}", `+systemFontStack())}
function measureFont(el,fstack){el.style.fontFamily=fstack;return el.getBoundingClientRect().width}
function render(){yearEl.textContent=(new Date()).getFullYear();setLayout(ui.layout);setLinkStyle(ui.linkStyle);setFavicons(ui.favicons);setTheme(ui.theme);renderCategories();renderLinks()}
function bind(){btnAddLink.onclick=()=>openLinkEditor(null);btnAddCategory.onclick=()=>{const name=prompt("New category name:");if(!name)return;categories.push({id:uid(),name:name.trim()});save(LS_CATS,categories);renderCategories()};btnOpenSettings.onclick=openSettings;btnCloseSettings.onclick=closeSettings;settingsOverlay.addEventListener("click",e=>{if(e.target===settingsOverlay)closeSettings()});btnCloseLink.onclick=closeLinkModal;linkOverlay.addEventListener("click",e=>{if(e.target===linkOverlay)closeLinkModal()});btnSaveLink.onclick=saveLink;btnDeleteLink.onclick=deleteLink;palette.addEventListener("click",e=>{const s=e.target.closest(".swatch");if(s)setColor(s.dataset.color)});syncRGB();btnImport.onclick=importJSON;fileImport.addEventListener("change",onImportFile);btnExport.onclick=exportJSON;setLayoutButtons();setSettingsBindings()}
function init(){ensureDefaults();buildPalette();populateBuiltInFonts();render();loadTLDs()}
init();
